### ISSUE TITLE
Question: System resource requirements

### ISSUE THREAD

**Issue by gayashanbc** [charliememory/Pose-Guided-Person-Image-Generation#16]
I would like to know what are the required system resources (i.e. CPU, GPU, RAM), in order to train and test this model?

**Comment by xuisshoe** [comment]
I was trying to test the model after training. But the testing output pictures seem to be extremely high in one  color channel, sometimes blue some times green. The training output is okay though. Any idea or suggestions ?

**Comment by xingyueyaohui** [comment]
> I was trying to test the model after training. But the testing output pictures seem to be extremely high in one color channel, sometimes blue some times green. The training output is okay though. Any idea or suggestions ?

I think trying another initialization may be of help, like Xavier initialization. The intuition to this may be that, without good initialization, the gradient on a single channel will be very large.

By the way, do you have any trained model? I'm very grateful if you can share yours with me.

**Comment by xuisshoe** [comment]
> > I was trying to test the model after training. But the testing output pictures seem to be extremely high in one color channel, sometimes blue some times green. The training output is okay though. Any idea or suggestions ?
> 
> I think trying another initialization may be of help, like Xavier initialization. The intuition to this may be that, without good initialization, the gradient on a single channel will be very large.
> 
> By the way, do you have any trained model? I'm very grateful if you can share yours with me.

Sorry man, I am using the downloaded model.

**Comment by leonardishere** [comment]
I hit a hardware setup that doesn't work. I'm using an Ubuntu VM with 2GB of RAM on a Windows 10 laptop. Looks like I'm going to have to shove this into AWS ¯\_(ツ)_/¯  
Stack trace below, showing the MemoryError that is thrown when simply trying to init the net. Also shown are some other issues that I haven't worked out yet.
```
$ ./run_DF_test.sh
/home/student/Documents/Pose-Guided-Person-Image-Generation/tflib/plot.py:4: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "main.py", line 4, in <module>
    from trainer import *
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/trainer.py", line 16, in <module>
    from models import *
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/models.py", line 5, in <module>
    import utils_wgan
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/utils_wgan.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')
in main of main.py
config.model=11
load pn_pairs_num ......
Uppercase local vars:
	BATCH_SIZE: 1
	DATA_DIR: 
	DIM: 64
	G_OUTPUT_DIM: 196608
	IMG_H: 128
	IMG_W: 64
	ITERS: 200000
	LAMBDA: 10
	MODE: dcgan
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
2019-02-27 21:03:32,135:WARNING::VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
2019-02-27 21:03:32,140:WARNING::VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
2019-02-27 21:03:35.913939: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main(config)
  File "main.py", line 27, in main
    trainer.init_net()
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/trainer.py", line 158, in init_net
    self.sess = sv.prepare_or_wait_for_session(config=sess_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 709, in prepare_or_wait_for_session
    self._write_graph()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 612, in _write_graph
    self._logdir, "graph.pbtxt")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/graph_io.py", line 69, in write_graph
    text_format.MessageToString(graph_def))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 165, in MessageToString
    printer.PrintMessage(message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 355, in PrintMessage
    self.PrintField(field, element)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 422, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 407, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 352, in PrintMessage
    self.PrintField(field, entry_submsg)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 422, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 407, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 357, in PrintMessage
    self.PrintField(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 422, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 407, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 357, in PrintMessage
    self.PrintField(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 422, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 407, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 357, in PrintMessage
    self.PrintField(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 386, in PrintField
    self.PrintFieldValue(field, value)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 440, in PrintFieldValue
    out.write(text_encoding.CEscape(out_value, out_as_utf8))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_encoding.py", line 79, in CEscape
    return ''.join(_cescape_byte_to_str[Ord(c)] for c in text)
MemoryError
2019-02-27 21:04:45.530250: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
ssim_G_x_mean: nan

ssim_G_x_std: nan

psnr_G_x_mean: nan

psnr_G_x_std: nan

L1_G_x_mean: nan

L1_G_x_std: nan

L2_G_x_mean: nan

L2_G_x_std: nan

Traceback (most recent call last):
  File "score.py", line 94, in <module>
    IS_G_mean, IS_G_std = tflib.inception_score.get_inception_score(G_list)
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/tflib/inception_score.py", line 27, in get_inception_score
    assert(type(images[0]) == np.ndarray)
IndexError: list index out of range
2019-02-27 21:04:49.085863: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:127: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
ssim_G_x_mean: nan

ssim_G_x_std: nan

psnr_G_x_mean: nan

psnr_G_x_std: nan

L1_G_x_mean: nan

L1_G_x_std: nan

L2_G_x_mean: nan

L2_G_x_std: nan

Traceback (most recent call last):
  File "score_mask.py", line 107, in <module>
    IS_G_mean, IS_G_std = tflib.inception_score.get_inception_score(G_list_masked)
  File "/home/student/Documents/Pose-Guided-Person-Image-Generation/tflib/inception_score.py", line 27, in get_inception_score
    assert(type(images[0]) == np.ndarray)
IndexError: list index out of range
```
