### ISSUE TITLE
ValueError: Cannot feed value of shape (100, 256, 256, 3) for Tensor u'ExpandDims:0', which has shape '(1, ?, ?, 3)'

### ISSUE THREAD

**Issue by SheelaRaju** [charliememory/Pose-Guided-Person-Image-Generation#20]
I have made changes in the lines:
By replacing o._shape = tf.TensorShape(new_shape) with  o.set_shape (tf.TensorShape(new_shape))
and  logits = tf.matmul(tf.squeeze(pool3), w) with logits = tf.matmul(tf.squeeze(pool3,[1,2]), w) to remove the previous errors but Now I am facing the below value error:

Traceback (most recent call last):
  File "score_mask.py", line 107, in <module>
    IS_G_mean, IS_G_std = tflib.inception_score.get_inception_score(G_list_masked)
  File "/mocapdata/Students/sheela/Pose-Guided-Person-Image-Generation/tflib/inception_score.py", line 46, in get_inception_score
    pred = sess.run(softmax, {'ExpandDims:0': inp})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 930, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1129, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (100, 256, 256, 3) for Tensor u'ExpandDims:0', which has shape '(1, ?, ?, 3)'

It would be really helpful if someone can give me the solution?

**Comment by SheelaRaju** [comment]
I solved it.
